trigger:
- master
- Release_*
- dev/*

jobs:
- job: Ubuntu_x64_limitexternaldependencies
  timeoutInMinutes: 90
  pool:
    vmImage: ubuntu-20.04
  variables:
    python: python=3.8
    boost_version: 1.71.0
    compiler: gxx_linux-64
    number_of_cores: nproc
    python_name: python38
  steps:
  - template: .azure-pipelines/linux_build_limitexternal.yml

